name: buildfork
on:
  push:
    branches:
      - main
      - featureX
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4.0.0
        with:
          path: ~/.npm
          key: buildCache
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: upload code coverage
        uses: actions/upload-artifact@v4.3.1
        with:
          name: codecoverage
          path: coverage
      - name: build
        run: npm run build
      - name: upload build files
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: build

          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: http://melted-chickens.surge.sh
    steps:
      - name: Download the build artifact
        uses: actions/download-artifact@v4.1.2
        with:
          name: build
      - name: deploy to surge
        run: npx surge --project '.' --domain melted-chickens.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          
      
          
      
